---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env: prod
    owner: Volodymyr-Korobtsov
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}-listener
      protocol: TCP
      port: 8888
      targetPort: 80
  type: NodePort
